name = input('Enter ur name:')
city = input('Enter ur city')
fav_food = input('Enter ur fav food:')
fav_game = input('Enter ur fav game')
fav_movie = input('Enter ur fav movie')
fav_sportperson = input('Enter ur fav sportperson')
fav_place = input('Enter ur fav place')
fav_song = input('Enter ur fav song')
fav_sports = input('Enter ur fav sports')
fav_singer = input('Enter ur fav singer')
print('!!!!INFO!!!!')
print(f'{name=}')
print(f'{city=}')
print(f'{fav_food=}')
print(f'{fav_game=}')
print(f'{fav_movie=}')
print(f'{fav_sportperson=}')
print(f'{fav_place=}')
print(f'{fav_song=}')
print(f'{fav_sports=}')
print(f'{fav_singer=}')

